// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKjYSNdGm95IVsBGC85aB_arG9lkKal5c',
    appId: '1:694660567151:web:95b6c681f738dc81a67d9a',
    messagingSenderId: '694660567151',
    projectId: 'cloud-functions-2fb4c',
    authDomain: 'cloud-functions-2fb4c.firebaseapp.com',
    storageBucket: 'cloud-functions-2fb4c.appspot.com',
    measurementId: 'G-SZ85E45DJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhZxT8CvUOSQnHmnIjjhRjchNWQ_iJ1H4',
    appId: '1:694660567151:android:220cf389f8cec0f2a67d9a',
    messagingSenderId: '694660567151',
    projectId: 'cloud-functions-2fb4c',
    storageBucket: 'cloud-functions-2fb4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-QZMAxJW6mnmdazsv1yAHeSl3FJI9faI',
    appId: '1:694660567151:ios:4345a65ef340b4f8a67d9a',
    messagingSenderId: '694660567151',
    projectId: 'cloud-functions-2fb4c',
    storageBucket: 'cloud-functions-2fb4c.appspot.com',
    iosClientId: '694660567151-f4augri0ake9hdt20nqsdfbhl987vpb0.apps.googleusercontent.com',
    iosBundleId: 'com.spielereinzig.firebasecloudfunctions.firebaseCloudFunctions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-QZMAxJW6mnmdazsv1yAHeSl3FJI9faI',
    appId: '1:694660567151:ios:4345a65ef340b4f8a67d9a',
    messagingSenderId: '694660567151',
    projectId: 'cloud-functions-2fb4c',
    storageBucket: 'cloud-functions-2fb4c.appspot.com',
    iosClientId: '694660567151-f4augri0ake9hdt20nqsdfbhl987vpb0.apps.googleusercontent.com',
    iosBundleId: 'com.spielereinzig.firebasecloudfunctions.firebaseCloudFunctions',
  );
}
